# Generated by Django 6.0.7 on 2026-08-05 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_attachment_id', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('content_id', models.CharField(blank=True, max_length=255)),
                ('is_inline', models.BooleanField(default=False)),
                ('content', models.BinaryField(blank=True, null=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('download_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_message_id', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('body_html', models.TextField(blank=True)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('ccRecipients', models.TextField(blank=True, help_text='Comma-separated list of CC recipients')),
                ('bccRecipients', models.TextField(blank=True, help_text='Comma-separated list of BCC recipients')),
                ('toRecipients', models.TextField(blank=True, help_text='Comma-separated list of TO recipients')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('folder', models.CharField(db_index=True, default='Inbox', max_length=60)),
            ],
            options={
                'db_table': 'portal_email',
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, default='bi-bell', max_length=40)),
                ('tone', models.CharField(default='primary', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AttachmentDownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_jobs', to='portal.attachment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('status', models.CharField(db_index=True, default='success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', related_query_name='email_attachment', to='portal.email'),
        ),
        migrations.CreateModel(
            name='OutlookAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('microsoft_user_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('paused', 'Paused')], db_index=True, default='active', max_length=20)),
                ('oauth_status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('is_default', models.BooleanField(default=True)),
                ('is_sync_paused', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('total_emails_synced', models.PositiveIntegerField(default=0)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('id_token_encrypted', models.TextField(blank=True)),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_token', to='portal.outlookaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GraphSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_id', models.CharField(db_index=True, max_length=120)),
                ('resource', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='created', max_length=20)),
                ('notification_url', models.CharField(max_length=255)),
                ('client_state', models.CharField(blank=True, max_length=255)),
                ('expiration_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('error', 'Error')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_subscriptions', to='portal.outlookaccount')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_link', models.TextField(blank=True)),
                ('last_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='portal.outlookaccount')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='outlook_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='portal.outlookaccount'),
        ),
        migrations.CreateModel(
            name='AccountHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_ok', models.BooleanField(default=False)),
                ('graph_ok', models.BooleanField(default=False)),
                ('webhook_ok', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='portal.outlookaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('sync', 'Sync'), ('refresh_token', 'Refresh Token'), ('download_attachments', 'Download Attachments'), ('renew_webhook', 'Renew Webhook'), ('health_check', 'Health Check')], db_index=True, max_length=30)),
                ('priority', models.IntegerField(db_index=True, default=5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=120)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='portal.outlookaccount')),
            ],
            options={
                'ordering': ('-priority', 'scheduled_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='started', max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('emails_processed', models.PositiveIntegerField(default=0)),
                ('emails_added', models.PositiveIntegerField(default=0)),
                ('emails_updated', models.PositiveIntegerField(default=0)),
                ('attachments_downloaded', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('worker', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='portal.outlookaccount')),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('email', 'graph_attachment_id'), name='uniq_email_graph_attachment'),
        ),
        migrations.AlterUniqueTogether(
            name='outlookaccount',
            unique_together={('user', 'email')},
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['outlook_account', 'received_at'], name='portal_emai_outlook_0d2718_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['outlook_account', 'is_read'], name='portal_emai_outlook_7ab998_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['outlook_account', 'folder', 'received_at'], name='portal_emai_outlook_de5739_idx'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('outlook_account', 'graph_message_id'), name='uniq_account_graph_message'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['account', '-start_time'], name='portal_sync_account_3266c0_idx'),
        ),
    ]
