# Generated by Django 6.0.7 on 2026-08-05 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='body_text',
            field=models.TextField(blank=True, help_text='Plain-text version of the body'),
        ),
        migrations.AddField(
            model_name='email',
            name='conversation_id',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='email',
            name='has_attachments',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='in_reply_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='email',
            name='internet_message_id',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='preview_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='reply_to',
            field=models.TextField(blank=True, help_text='Comma-separated reply-to addresses'),
        ),
        migrations.AddField(
            model_name='email',
            name='thread_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('icon', models.CharField(blank=True, default='bi-tag', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='email',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='emails', to='portal.category'),
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('to', 'To'), ('cc', 'Cc'), ('bcc', 'Bcc')], db_index=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.EmailField(max_length=254)),
                ('position', models.PositiveIntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='portal.email')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='email',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='emails', to='portal.tag'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['outlook_account', 'conversation_id'], name='portal_emai_outlook_ab844c_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['outlook_account', 'is_draft', 'updated_at'], name='portal_emai_outlook_b0499f_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['outlook_account', 'is_sent', 'received_at'], name='portal_emai_outlook_539958_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['conversation_id', 'received_at'], name='portal_emai_convers_ff46a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['email', 'recipient_type'], name='portal_emai_email_i_8bff9f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['address'], name='portal_emai_address_d5c6a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
    ]
